version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: passio-mysql-dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passio_root_pass
      MYSQL_DATABASE: passio_dev
      MYSQL_USER: passio_user
      MYSQL_PASSWORD: passio_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql
      - ./database/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - passio-dev-network

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: passio-redis-dev
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - passio-dev-network

  # Backend Development Server
  backend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: backend-dev
    container_name: passio-backend-dev
    restart: always
    environment:
      NODE_ENV: development
      PORT: 8000
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: passio_dev
      DB_USER: passio_user
      DB_PASSWORD: passio_pass
      REDIS_URL: redis://redis:6379
      JWT_SECRET: dev-jwt-secret
      ENCRYPTION_KEY: dev-encryption-key-32-chars-long
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./packages/backend:/app/packages/backend
      - backend_dev_node_modules:/app/packages/backend/node_modules
      - backend_dev_uploads:/app/uploads
    networks:
      - passio-dev-network

  # Frontend Development Server
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: frontend-dev
    container_name: passio-frontend-dev
    restart: always
    environment:
      VITE_API_URL: http://localhost:8000
      VITE_APP_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - backend-dev
    volumes:
      - ./packages/frontend:/app/packages/frontend
      - frontend_dev_node_modules:/app/packages/frontend/node_modules
    networks:
      - passio-dev-network

  # Database management tool
  adminer:
    image: adminer
    container_name: passio-adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    depends_on:
      - mysql
    networks:
      - passio-dev-network

volumes:
  mysql_dev_data:
    driver: local
  redis_dev_data:
    driver: local
  backend_dev_node_modules:
    driver: local
  frontend_dev_node_modules:
    driver: local
  backend_dev_uploads:
    driver: local

networks:
  passio-dev-network:
    driver: bridge 